ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER motor_ledger IDENTIFIED BY ml123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CREATE MATERIALIZED VIEW,
    CREATE PROCEDURE,
    CREATE SEQUENCE,
    CREATE SESSION,
    CREATE SYNONYM,
    CREATE TABLE,
    CREATE TRIGGER,
    CREATE TYPE,
    CREATE VIEW
    TO motor_ledger;