CREATE TABLE brands
(
    brand_id   NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    brand_name VARCHAR2(100 CHAR) NOT NULL
);

CREATE TABLE models
(
    model_id           NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    model_name         VARCHAR2(120 CHAR) NOT NULL,
    model_displacement NUMBER(6, 2) NOT NULL,
    model_base_price   NUMBER(14, 2) NOT NULL,
    brand_id           NUMBER(10) NOT NULL
);

CREATE TABLE users
(
    user_id      NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    user_name    VARCHAR2(200 CHAR) NOT NULL,
    user_address VARCHAR2(400 CHAR) NOT NULL,
    user_phone   VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE trade_ins
(
    trade_in_id              NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    trade_in_plate           VARCHAR2(10 CHAR) NOT NULL,
    trade_in_appraisal_price NUMBER(14, 2) NOT NULL,
    trade_in_cession_date    DATE NOT NULL,
    trade_in_customer_id     NUMBER(10) NOT NULL,
    trade_in_model_id        NUMBER(10) NOT NULL
);

CREATE TABLE options
(
    option_id          NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    option_name        VARCHAR2(100 CHAR) NOT NULL,
    option_description VARCHAR2(4000 CHAR)
);

CREATE TABLE model_options
(
    model_option_id NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY,
    model_price     NUMBER(14, 2) NOT NULL,
    model_id        NUMBER(10) NOT NULL,
    option_id       NUMBER(10) NOT NULL
);

CREATE TABLE sales
(
    sale_id          NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    sale_date        TIMESTAMP NOT NULL,
    sale_new_plate   VARCHAR2(10 CHAR) NOT NULL,
    sale_total_price NUMBER(14, 2) NOT NULL,
    sale_customer_id NUMBER(10) NOT NULL,
    sale_seller_id   NUMBER(10) NOT NULL,
    sale_model_id    NUMBER(10) NOT NULL,
    trade_in_id      NUMBER(10)
);

CREATE TABLE sale_options
(
    sale_option_id       NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY
    NOT NULL,
    option_price_at_sale NUMBER(14, 2) NOT NULL,
    sale_id              NUMBER(10) NOT NULL,
    model_option_id      NUMBER(10) NOT NULL
);