CREATE TABLE brands (
    brand_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand_name varchar(100) NOT NULL
);
CREATE TABLE models (
    model_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_name varchar(120) NOT NULL,
    model_displacement numeric(6, 2) NOT NULL,
    model_base_price numeric(14, 2) NOT NULL,
    brand_id integer NOT NULL
);
CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name varchar(200) NOT NULL,
    user_address varchar(400) NOT NULL,
    user_phone varchar(20) NOT NULL
);
CREATE TABLE trade_ins (
    trade_in_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trade_in_plate varchar(10) NOT NULL,
    trade_in_appraisal_price numeric(14, 2) NOT NULL,
    trade_in_cession_date date NOT NULL,
    trade_in_customer_id integer NOT NULL,
    trade_in_model_id integer NOT NULL
);
CREATE TABLE options (
    option_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    option_name varchar(100) NOT NULL,
    option_description text
);
CREATE TABLE model_options (
    model_option_id integer GENERATED BY DEFAULT AS IDENTITY,
    model_price numeric(14, 2) NOT NULL,
    model_id integer NOT NULL,
    option_id integer NOT NULL
);
CREATE TABLE sales (
    sale_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_date timestamp NOT NULL,
    sale_new_plate varchar(10) NOT NULL,
    sale_total_price numeric(14, 2) NOT NULL,
    sale_customer_id integer NOT NULL,
    sale_seller_id integer NOT NULL,
    sale_model_id integer NOT NULL,
    trade_in_id integer
);
CREATE TABLE sale_options (
    sale_option_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    option_price_at_sale numeric(14, 2) NOT NULL,
    sale_id integer NOT NULL,
    model_option_id integer NOT NULL
);